version: "3.7"

services:
  backend:
    container_name: structure-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
       - ./backend:/usr/src/app
       - /usr/src/app/node_modules

  frontend:
    container_name: structure-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
       - ./frontend:/usr/src/app
       - /usr/src/app/node_modules