version: "3.7"

services:
  backend:
    container_name: structure-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - MONGO_CONNECTION_STRING=mongodb+srv://admin123:admin123@cluster0.jqvox.gcp.mongodb.net/structure?retryWrites=true&w=majority

  frontend:
    container_name: structure-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
