name: Deploy static website to AWS S3 bucket

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    
    - name: Install dependencies
      run: |
        cd ./frontend
        npm install

    - name: Generate .env file
      run: |
        FILE="./frontend/src/env.ts"
        # echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> ./frontend/.env
        SECRET_LIST=$(sed -r 's/.*(REACT_APP\w*).*/\1/g' $FILE | grep "REACT")
        while read -r line
        do
          echo "echo \"${line}=\\\$\{\{ secrets.${line} \}\}\" >> ./frontend/.env" >> .tmp
        done <<< "$SECRET_LIST"

        if [ -f "./.tmp" ]; then
          n=1
          while read line; do
          # reading each line
            echo "Line No. $n"
            echo "$line"
            `$line`
            n=$((n+1))
          done < "./.tmp"
        fi



    - name: Build static website
      run: |
        cd ./frontend
        npm run build

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./frontend/build/ s3://structure.geeks.academy --acl public-read --delete
