name: NodeJS Build & Test Backend

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      working-directory: ./backend

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn

      - name: Install dependencies for backend
        run: yarn install --frozen-lockfile

      - name: Build the backend
        run: yarn build

      - name: Run tests for backend
        run: yarn test
