name: Slack Project Notifier

on:
  project_card:
      types: [moved]
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Magical Slack Notifier
        uses: hayuna/github-action-slack-project-notifier@1.2.1
        with:
          USERNAME: Project Manager
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          PROJECT: ${{ secrets.PROJECT }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
